version: '3.8'

services:
  mpsc-api:
    build:
      dockerfile: ./BetterCoding.MessagePubSubCenter.API/Dockerfile
      context: ./
    image: bc-mpsc-api:latest
    restart: always
    container_name: mpsc-api
    env_file: 
      - ./BetterCoding.MessagePubSubCenter.API/.env
    ports:
      - '8080:80'
    networks:
      - rabbitmq
      - elasticsearch
      - mpsc
      - strapi

networks:
  rabbitmq:
    external: true
  elasticsearch:
    external: true
  strapi:
    external: true    
  mpsc:
    external: true