services:

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    restart: always
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elasticsearch

networks:
  elasticsearch:
    external: true    