services:

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
      - 8000:8000
      
volumes:
  portainer_data: