version: '3.8'

services:
  redis:
    image: bitnami/redis:latest
    # deploy:
    #     resources:
    #         limits:
    #           cpus: '0.20'
    #           memory: 200M
    #         reservations:
    #           cpus: '0.10'
    #           memory: 100M    
    container_name: redis
    env_file:
      - .env  
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - '8379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - redis

volumes:
  redis_data:
    driver: local

networks:
  redis:
    name: redis
    driver: bridge